setup installation only

diff --git a/ubuntu/nginx15 b/ubuntu/nginx15
--- a/ubuntu/nginx15
+++ b/ubuntu/nginx15
@@ -1,90 +1,195 @@
 #!/bin/sh
+
 ### BEGIN INIT INFO
-# Provides:          nginx
-# Required-Start:    $remote_fs $syslog
-# Required-Stop:     $remote_fs $syslog
+# Provides:       nginx
+# Required-Start:    $local_fs $remote_fs $network $syslog $named
+# Required-Stop:     $local_fs $remote_fs $network $syslog $named
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: nginx init.d dash script for Ubuntu or other *nix.
-# Description:       nginx init.d dash script for Ubuntu or other *nix.
+# Short-Description: starts the nginx web server
+# Description:       starts nginx using start-stop-daemon
 ### END INIT INFO
-#------------------------------------------------------------------------------
-# nginx - this Debian Almquist shell (dash) script, starts and stops the nginx
-#         daemon for Ubuntu and other *nix releases.
-#
-# description:  Nginx is an HTTP(S) server, HTTP(S) reverse \
-#               proxy and IMAP/POP3 proxy server.  This \
-#               script will manage the initiation of the \
-#               server and it's process state.
-#
-# processname: nginx
-# Provides:    nginx
-#
-# Author:  Zubair Hamid
-#          <zubairhamid AT cloudmpower.com>.
-#
-# Notes: nginx init.d dash script for Ubuntu.
-# Tested with: Ubuntu 15.10, nginx-1.9.11
-#
-#
-#------------------------------------------------------------------------------
-#                               MIT X11 License
-#------------------------------------------------------------------------------
-#
-# Copyright (c) 2008-2019 Zubair Hamid
-#
-# Permission is hereby granted, free of charge, to any person obtaining
-# a copy of this software and associated documentation files (the
-# "Software"), to deal in the Software without restriction, including
-# without limitation the rights to use, copy, modify, merge, publish,
-# distribute, sublicense, and/or sell copies of the Software, and to
-# permit persons to whom the Software is furnished to do so, subject to
-# the following conditions:
-#
-# The above copyright notice and this permission notice shall be
-# included in all copies or substantial portions of the Software.
-#
-# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
-# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
-# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
-# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
-# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
-# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
-# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
-#------------------------------------------------------------------------------
 
-#------------------------------------------------------------------------------
-#                               Function
-#------------------------------------------------------------------------------
+PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
+DAEMON=/usr/local/nginx/sbin/nginx
+NAME=nginx
+DESC=nginx
 
-LSB_FUNC=/lib/lsb/init-functions
+# Include nginx defaults if available
+if [ -r /usr/local/nginx ]; then
+        . /usr/local/nginx
+fi
 
-# Test that init functions exists
-test -r $LSB_FUNC || {
-    echo "$0: Cannot find $LSB_FUNC! Script exiting." 1>&2
-    exit 5
+STOP_SCHEDULE="${STOP_SCHEDULE:-QUIT/5/TERM/5/KILL/5}"
+
+test -x $DAEMON || exit 0
+
+. /lib/init/vars.sh
+. /lib/lsb/init-functions
+
+# Try to extract nginx pidfile
+PID=$(cat /usr/local/nginx/conf/nginx.conf | grep -Ev '^\s*#' | awk 'BEGIN { RS="[;{}]" } { if ($1 == "pid") print $2 }' | head -n1)
+if [ -z "$PID" ]; then
+        PID=/usr/local/nginx/logs/nginx.pid
+fi
+
+if [ -n "$ULIMIT" ]; then
+        # Set ulimit if it is set in /etc/default/nginx
+        ulimit $ULIMIT
+fi
+
+start_nginx() {
+        # Start the daemon/service
+        #
+        # Returns:
+        #   0 if daemon has been started
+        #   1 if daemon was already running
+        #   2 if daemon could not be started
+        start-stop-daemon --start --quiet --pidfile $PID --exec $DAEMON --test > /dev/null \
+                || return 1
+        start-stop-daemon --start --quiet --pidfile $PID --exec $DAEMON -- \
+                $DAEMON_OPTS 2>/dev/null \
+                || return 2
 }
 
-. $LSB_FUNC
-description "nginx http daemon"
-author "zubair hamid <zubairhamid@cloudmpower.com>"
+test_config() {
+        # Test the nginx configuration
+        $DAEMON -t $DAEMON_OPTS >/dev/null 2>&1
+}
 
-start on (filesystem and net-device-up IFACE=lo)
-stop on runlevel [!2345]
+stop_nginx() {
+        # Stops the daemon/service
+        #
+        # Return
+        #   0 if daemon has been stopped
+        #   1 if daemon was already stopped
+        #   2 if daemon could not be stopped
+        #   other if a failure occurred
+        start-stop-daemon --stop --quiet --retry=$STOP_SCHEDULE --pidfile $PID --name $NAME
+        RETVAL="$?"
+        sleep 1
+        return "$RETVAL"
+}
 
-env DAEMON=/usr/local/nginx/sbin/nginx
-env PID=/var/run/nginx.pid
+reload_nginx() {
+        # Function that sends a SIGHUP to the daemon/service
+        start-stop-daemon --stop --signal HUP --quiet --pidfile $PID --name $NAME
+        return 0
+}
 
-expect fork
-respawn
-respawn limit 10 5
-#oom never
+rotate_logs() {
+        # Rotate log files
+        start-stop-daemon --stop --signal USR1 --quiet --pidfile $PID --name $NAME
+        return 0
+}
 
-pre-start script
-        $DAEMON -t
-        if [ $? -ne 0 ]
-                then exit $?
-        fi
-end script
+upgrade_nginx() {
+        # Online upgrade nginx executable
+        # http://nginx.org/en/docs/control.html
+        #
+        # Return
+        #   0 if nginx has been successfully upgraded
+        #   1 if nginx is not running
+        #   2 if the pid files were not created on time
+        #   3 if the old master could not be killed
+        if start-stop-daemon --stop --signal USR2 --quiet --pidfile $PID --name $NAME; then
+                # Wait for both old and new master to write their pid file
+                while [ ! -s "${PID}.oldbin" ] || [ ! -s "${PID}" ]; do
+                        cnt=`expr $cnt + 1`
+                        if [ $cnt -gt 10 ]; then
+                                return 2
+                        fi
+                        sleep 1
+                done
+                # Everything is ready, gracefully stop the old master
+                if start-stop-daemon --stop --signal QUIT --quiet --pidfile "${PID}.oldbin" --name $NAME; then
+                                        return 0
+                                else
+                                        return 3
+                                fi
+                        else
+                                return 1
+                        fi
+                }
 
-exec $DAEMON
+case "$1" in
+        start)
+                log_daemon_msg "Starting $DESC" "$NAME"
+                start_nginx
+                case "$?" in
+                        0|1) log_end_msg 0 ;;
+                        2)   log_end_msg 1 ;;
+                esac
+                ;;
+        stop)
+                log_daemon_msg "Stopping $DESC" "$NAME"
+                stop_nginx
+                case "$?" in
+                        0|1) log_end_msg 0 ;;
+                        2)   log_end_msg 1 ;;
+                esac
+                ;;
+        restart)
+                log_daemon_msg "Restarting $DESC" "$NAME"
+
+                # Check configuration before stopping nginx
+                if ! test_config; then
+                    log_end_msg 1 # Configuration error
+                    exit $?
+                fi
+
+                stop_nginx
+                case "$?" in
+                    0|1)
+                        start_nginx
+                        case "$?" in
+                            0) log_end_msg 0 ;;
+                            1) log_end_msg 1 ;; # Old process is still running
+                            *) log_end_msg 1 ;; # Failed to start
+                            esac
+                            ;;
+                            *)
+                            # Failed to stop
+                            log_end_msg 1
+                            ;;
+                            esac
+                            ;;
+        reload|force-reload)
+            log_daemon_msg "Reloading $DESC configuration" "$NAME"
+
+            # Check configuration before stopping nginx
+            #
+            # This is not entirely correct since the on-disk nginx binary
+            # may differ from the in-memory one, but that's not common.
+            # We prefer to check the configuration and return an error
+            # to the administrator.
+            if ! test_config; then
+            log_end_msg 1 # Configuration error
+            exit $?
+            fi
+                reload_nginx
+                log_end_msg $?
+                ;;
+        configtest|testconfig)
+            log_daemon_msg "Testing $DESC configuration"
+            test_config
+            log_end_msg $?
+             ;;
+        status)
+             status_of_proc -p $PID "$DAEMON" "$NAME" && exit 0 || exit $?
+             ;;
+        upgrade)
+             log_daemon_msg "Upgrading binary" "$NAME"
+             upgrade_nginx
+             log_end_msg $?
+             ;;
+        rotate)
+                log_daemon_msg "Re-opening $DESC log files" "$NAME"
+                rotate_logs
+                log_end_msg $?
+                ;;
+        *)
+                echo "Usage: $NAME {start|stop|restart|reload|force-reload|status|configtest|rotate|upgrade}" >&2
+                exit 3
+                ;;
+esac
